routes/web.php
<?php

Route::get('/', [
    'uses' => 'ShopController@home',
    'as' => 'shop.home'
]);

Route::group(['prefix' => 'shop'], function () {

    Route::get('/product/detail/{slug}', [
        'uses' => 'ShopController@detail',
        'as' => 'product.detail'
    ]);
    Route::get('/product/{cat}/{name}/{id}', [
        'uses' => 'ShopController@category',
        'as' => 'product.category'
    ]);
    Route::get('/brand/{name}', [
        'uses' => 'ShopController@brand',
        'as'  => 'brand.products'
    ]);
    Route::get('/login', [
        'uses' => 'ShopController@signup',
        'as' => 'shop.login'
    ]);
    Route::get('/track', [
        'uses' => 'ShopController@track_orders',
        'as' => 'shop.track-orders'
    ]);
    Route::post('/track', [
        'uses' => 'ShopController@track',
        'as' => 'track'
    ]);
    Route::post('/search',[
        'uses' => 'ShopController@search',
        'as' => 'shop.search'
    ]);
    Route::get('/search',[
        'uses' => 'ShopController@search',
        'as' => 'shop.search'
    ]);
    Route::get('/history',[
        'uses' => 'ShopController@history',
        'as' => 'shop.history'
    ]);
    Route::post('/history',[
        'uses' => 'ShopController@show_history',
        'as' => 'shop.records'
    ]);
    Route::get('/{provider}/auth',[
        'uses' => 'ShopController@auth',
        'as' => 'social.auth'
    ]);
    Route::get('/{provider}/redirect',[
        'uses' => 'ShopController@auth_callback',
        'as' => 'social.callback'
    ]);

    // shopping cart
    Route::get('/cart/add/{id}', [
        'uses' => 'ShoppingCartController@add_to_cart',
        'as'   => 'cart.add'
    ]);
    Route::post('/cart/add/{id}', [
        'uses' => 'ShoppingCartController@add_to_cart',
        'as'   => 'cart.add'
    ]);
    Route::get('/cart', [
        'uses' => 'ShoppingCartController@show',
        'as' => 'cart'
    ]);
    Route::get('/cart/incr/{id}', [
        'uses' => 'ShoppingCartController@incr',
        'as' => 'cart.incr'
    ]);
    Route::get('/cart/dec/{id}', [
        'uses' => 'ShoppingCartController@decr',
        'as' => 'cart.decr'
    ]);
    Route::get('/cart/remove/{id}', [
        'uses' => 'ShoppingCartController@remove',
        'as' => 'cart.remove'
    ]);

    //checkout
    Route::get('/checkout', [
        'uses' => 'ShoppingCartController@checkout',
        'as' => 'checkout'
    ]);
    
    //paystack
    Route::post('/pay', [
        'uses' => 'PaymentController@redirectToGateway',
        'as' => 'pay'
    ]);
    Route::get('/payment/callback', [
        'uses' => 'PaymentController@handleGatewayCallback',
        'as' => 'pmtcallback'
    ]);
    Route::get('/cashondelivery', [
        'uses' => 'PaymentController@cash_on_delivery',
        'as' => 'cash.delivery'
    ]);
});


Route::group(['prefix' => 'admin'], function () {

    Route::get('/login', [
        'uses' => 'Auth\AdminLoginController@showloginform',
        'as' => 'login.form'
    ]);
    Route::post('/login/submit', [
        'uses' => 'Auth\AdminLoginController@login',
        'as' => 'login.submit'
    ]);
    Route::get('/', [
        'uses' => 'AdminController@index',
        'as' => 'dashboard'
    ]);
    Route::get('/status',[
        'uses' => 'ProductsController@status',
        'as' => 'admin.status'
    ]);
    Route::get('/orders',[
        'uses' => 'ProductsController@allOrders',
        'as' => 'admin.all-orders'
    ]);
    Route::get('/items',[
        'uses' => 'ProductsController@items',
        'as' => 'admin.items'
    ]);

    Route::post('/logout', [
        'uses' => 'Auth\AdminLoginController@logout',
        'as' => 'admin.logout'
    ]);


    //password reset routes
    Route::post('/password/email', [
        'uses' => 'Auth\AdminForgotPasswordController@sendResetLinkEmail',
        'as' => 'admin.password.email'
    ]);

    Route::get('/password/reset', [
        'uses' => 'Auth\AdminForgotPasswordController@showLinkRequestForm',
        'as' => 'admin.password.request'
    ]);

    Route::post('/password/reset', [
        'uses' => 'Auth\AdminResetPasswordController@reset',
        'as' => 'admin.password.update'
        ]);

    Route::get('/password/reset/{token}', [
        'uses' => 'Auth\AdminResetPasswordController@showResetForm',
        'as' => 'admin.password.reset'
    ]);

    //categories
    Route::get('/category/new', [
        'uses' => 'CategoryController@create',
        'as' => 'admin.category.new'
    ]);

    Route::post('/category/submit', [
        'uses' => 'CategoryController@store',
        'as' => 'admin.category.submit'
    ]);
    Route::get('/category/all', [
        'uses' => 'CategoryController@index',
        'as' => 'admin.category.all'
    ]);
    Route::get('/category/edit/{id}', [
        'uses' => 'CategoryController@edit',
        'as' => 'admin.category.edit'
    ]);
    Route::post('/category/update/{id}', [
        'uses' => 'CategoryController@update',
        'as' => 'admin.category.update'
    ]);
    Route::get('/category/newsub', [
        'uses' => 'CategoryController@createsub',
        'as' => 'admin.category.newsubcat'
    ]);
    Route::get('/category/allsubcat',[
        'uses' => 'CategoryController@all_subcat',
        'as' => 'admin.category.allsubcat'
    ]);
    Route::get('/category/subcat/edit/{id}',[
        'uses' => 'CategoryController@edit_subcat',
        'as'  => 'admin.category.editsubcat'
    ]);
    Route::post('/category/subcat/edit/{id}',[
        'uses'  => 'CategoryController@update_subcat',
        'as'   =>  'admin.category.updatesubcat'
    ]);
    Route::get('/category/newsubsub', [
        'uses' => 'CategoryController@createsubsub',
        'as' => 'admin.category.newsubsubcat'
    ]);
    Route::post('/category/newsub', [
        'uses' => 'CategoryController@submitsubcat',
        'as' => 'admin.category.submitsubcat'
    ]);

    //brands
    Route::get('/category/brands', [
        'uses' => 'CategoryController@brands',
        'as'   => 'admin.category.brands'
    ]);
    Route::get('/category/brands/new', [
        'uses' => 'CategoryController@brandnew',
        'as' => 'admin.category.brands.new'
    ]);
    Route::post('/category/brands/new', [
        'uses' => 'CategoryController@brandsave',
        'as' => 'admin.category.brands.new'
    ]);

    //products
    Route::get('/products/new', [
        'uses' => 'ProductsController@create',
        'as' => 'admin.products.new'
    ]);
    Route::post('/products/save', [
        'uses' => 'ProductsController@store',
        'as' => 'admin.products.save'
    ]);
    Route::get('/products/all', [
        'uses' => 'ProductsController@index',
        'as' => 'admin.products.all'
    ]);
    Route::get('/products/edit/{id}', [
        'uses' => 'ProductsController@edit',
        'as' => 'admin.products.edit'
    ]);
    Route::post('/products/update/{id}', [
        'uses' => 'ProductsController@update',
        'as' => 'admin.products.update'
    ]);
    Route::get('/products/viewdetails/{id}', [
        'uses' => 'ProductsController@show',
        'as' => 'admin.products.viewdetails'
    ]);
    Route::get('/products/delete/{id}', [
        'uses' => 'ProductsController@destroy',
        'as' => 'admin.products.delete'
    ]);
    Route::get('/products/trashed', [
        'uses' => 'ProductsController@trashed',
        'as' => 'admin.products.trashed'
    ]);
    Route::get('/products/destroy/{id}', [
        'uses' => 'ProductsController@kill',
        'as' => 'admin.products.destroy'
    ]);
    Route::get('/products/restore/{id}', [
        'uses' => 'ProductsController@restore',
        'as' => 'admin.products.restore'
    ]);

    //customers
    Route::get('/customers',[
        'uses' => 'ProductsController@customers',
        'as' => 'admin.customers'
    ]);
    Route::get('/invoices',[
        'uses' => 'ProductsController@invoices',
        'as' => 'admin.invoices'
    ]);
    Route::get('/unpaid',[
        'uses' => 'ProductsController@unpaid',
        'as' => 'admin.unpaid'
    ]);
});
//ajax
Route::post('/ajaxcat ', [
    'uses' => 'CategoryController@ajaxcat',
    'as' => 'admin.category.ajaxcat'
]);
Route::post('/ajaxsubcat', [
    'uses' => 'CategoryController@ajaxsubcat',
    'as' => 'admin.category.ajaxsubcat'
]);


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $dates =['deleted_at'];

    protected $fillable = [
        'name',
        'price',
        'description',
        'image',
        'slug',
        'status',
        'discount',
        'stock',
        'color',
        'size',
        'brand_id',
        'category_id',
        'subcategory_id',
        'subsubcategory_id'

    ];
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function brand()
    {
        return $this->belongsTo('App\Brand');
    }

    
    public function thumbnails()
    {
        return $this->hasMany('App\Thumbnail');
    }

    public function subcategory()
    {
        return $this->belongsTo('App\SubCategory');
    }

    public function subsubcategory()
    {
        return $this->belongsTo('App\SubsubCategory');
    }

    public function getFormatedPriceAttribute(){

        return number_format($this->price,2);

    }
    
    public function getDiscountPriceAttribute(){

        return number_format($this->price - (($this->discount/100) * $this->price),2);
        
    }
}

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Session;
use SocialAuth;
use Auth;
use App\Order;
use App\Brand;
use App\Invoice;
use App\Product;
use App\OrderItem;
use App\Category;
use App\SubCategory;
use App\SubsubCategory;
use App\CashOnDeliveryInvoice;

class ShopController extends Controller
{
    public function home()
    {

        
//hot deals
        $hotdeals = Product::where('status', 'hotdeal')->orderBy('created_at', 'desc')->take(3)->get();

        $all = Product::where('status', 'newproduct')->orderBy('created_at', 'desc')->take(6)->get();

  //new shoes for boys and girls
        $boysshoescat = Subsubcategory::where('name', 'FootWear For Boys')->get();
        $girlsshoescat = Subsubcategory::where('name', 'FootWear For Girls')->get();
        $boyssheoescatid = $boysshoescat[0]->id;
        $girlsshoescatid = $girlsshoescat[0]->id;
        $prdtboys = Product::where('status', 'newproduct')->where('subsubcategory_id', $boyssheoescatid)->orderBy('created_at', 'desc')->take(3)->get();
        $prdtgirls = Product::where('status', 'newproduct')->where('subsubcategory_id', $girlsshoescatid)->orderBy('created_at', 'desc')->take(3)->get();
        $newShoes = collect([$prdtboys,$prdtgirls])->collapse();

// //new cloths
        $boysClothsCat = SubCategory::where('name', 'boys fashion')->get();
        $boysNewCloths = Product::where('status', 'newproduct')->where('subcategory_id', $boysClothsCat[0]->id)->orderBy('created_at', 'desc')->take(3)->get();
        $girlsClothsCat = SubCategory::where('name', 'girls fashion')->get();
        $girlsNewCloths = Product::where('status', 'newproduct')->where('subcategory_id', $girlsClothsCat[0]->id)->orderBy('created_at', 'desc')->take(3)->get();
        $newCloths = collect([$girlsNewCloths,$boysNewCloths])->collapse();

        $catToys = Category::where('name', 'toys')->get();
        $newToys = Product::where('status', 'newproduct')->where('category_id', $catToys[0]->id)->orderBy('created_at', 'desc')->take(5)->get();

  //featured
        $featured = Product::where('status', 'featured')->orderBy('created_at', 'desc')->get();

  //best seller
        $bestseller = Product::where('status', 'bestseller')->orderBy('created_at', 'desc')->get();

  //new arrivals
        $newArrivals = Product::where('status', 'newarrival')->orderBy('created_at', 'desc')->get();

  //4 mums
        $mums = Product::where('status', '4mums')->orderBy('created_at', 'desc')->get();

  
        return view('welcome')->with('hotdeals', $hotdeals)
                            ->with('newcloths', $newCloths)
                            ->with('newToys', $newToys)
                            ->with('newShoes', $newShoes)
                            ->with('featured', $featured)
                            ->with('bestseller', $bestseller)
                            ->with('newArrivals', $newArrivals)
                            ->with('mums',$mums)
                            ->with('all', $all);

    }

    public function detail(Request $request, $slug)
    {

        $prdt = Product::where('slug', $slug)->get();

      
      //get product in the same sub or subsub category as related products
        $catId = '';
        $cat ='';

        if ($prdt[0]->subsubcategory) {
            $catId = $prdt[0]->subsubcategory_id;
            $cat = 'subsubcategory_id';
        } else {
            $catId = $prdt[0]->subcategory_id;
            $cat = 'subcategory_id';
        }

        $relatedPrdt = Product::where($cat, $catId)->orderBy('created_at', 'desc')->take(7)->get();

        return view('shop.detail')->with('prdt', $prdt)
                                ->with('relatedPrdt', $relatedPrdt);
    }

    public function category(Request $request, $cat, $name, $id)
    {
        $category = $cat.'_id';


        $catproducts = Product::where($category, $id)->orderBy('created_at', 'desc')->paginate(16);


        return view('shop.category')->with('catproducts', $catproducts)
                                    ->with('cat', $cat)
                                    ->with('catName', $name);
    }

    public function brand($name)
    {

        $brandName = $name;
      
         $brd = Brand::where('name', $name)->get();

         $brandPrdt = Product::where('brand_id', $brd[0]->id)->paginate(16);

        return view('shop.brand')->with('brandPrdt', $brandPrdt)
                              ->with('brandName', $brandName);
    }

    public function signup()
    {
        return view('shop.signup');
    }

    public function track_orders()
    {

        return view('shop.track-order');
    }

    public function track(Request $request)
    {
     // tracking code
      $trackingCode = $request->code;
      $ord;

      // get order using invoice number
     $ord = Order::with('orderItems')->where('tracking_code',$trackingCode)->get();

     // if code was not found check cash on delivery
     if($ord->isEmpty()){

        $ord = CashOnDeliveryOrder::with('orderitems')->where('tracking_code',$trackingCode)->get();

      
     }else{
        Session::flash('info','the tracking code was not found in our records');

        return redirect()->back();
     }

      return view('shop.track-order')->with('ord',$ord);
                                    
    }

    public function search(Request $request)
    {
        $q = $request->q;
        $rslt = Product::where('name','LIKE','%'.$q.'%')->paginate(16);

        if($rslt->isEmpty()){
            Session::flash('info','Your search term '. $q .' did not return any products. Please try again');
            return back();
        }

        return view('shop.search')->with('result',$rslt)
                                ->with('q',$q);
    }

    public function history()
    {
      return view('shop.history');  
    }

    public function show_history(Request $request)
    {
        
         $hist = Invoice::with(['user','order'])->where('user_id',Auth::user()->id)->whereBetween('created_at', [$request->from, $request->ending])->get();
        
        $cshOnDel = CashOnDeliveryInvoice::with(['user','cash_on_delivery_order'])->where('user_id',Auth::user()->id)->whereBetween('created_at', [$request->from, $request->ending])->get();
            
        return view('shop.history')->with('hist', $hist)
                                    ->with('cshOnDel',$cshOnDel);
    }

    // public function auth($provider)
    // {
    //     return SocialAuth::authorize($provider);
    // }

    // public function auth_callback($provider)
    // {

    //     SocialAuth::login($provider, function($user, $details){
    //         $user->name = $details->full_name;
    //         $user->email = $details->email;
    //         $user->save();
    //         //dd($details);
    //     });

    //     return redirect('shop.home');
    // }
}

resources/views/shop/cart.blade.php
@extends('shop.layout.main')

@section('content')
  <div class="breadcrumb">
      <div class="container">
        <div class="breadcrumb-inner">
          <ul class="list-inline list-unstyled">
          <li><a href="{{ route('shop.home')}}">Home</a></li>
            <li class='active'>Shopping Cart</li>
          </ul>
        </div><!-- /.breadcrumb-inner -->
      </div><!-- /.container -->
    </div>

    <div class="body-content outer-top-xs">
        <div class="container">
          <div class="row ">
            <div class="shopping-cart">
              <div class="shopping-cart-table ">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th class="cart-romove item">Remove</th>
                <th class="cart-description item">Image</th>
                <th class="cart-product-name item">Name</th>
                <th class="cart-product-name item">Price</th>
                <th class="cart-edit item"></th>
                <th class="cart-qty item">Quantity</th>
                <th class="cart-sub-total item">Subtotal</th>
              </tr>
            </thead><!-- /thead -->
            <tfoot>
              <tr>
                <td colspan="7">
                  <div class="shopping-cart-btn">
                    <span class="">
                      <a href="{{ route('shop.home')}}" class="btn btn-upper btn-primary outer-left-xs">Continue Shopping</a>
                    </span>
                  </div><!-- /.shopping-cart-btn -->
                </td>
              </tr>
            </tfoot>
            <tbody>
              @if(Cart::isEmpty())
              <tr class="text-center"><td colspan="100%"><p style="font-size:20px"><i>you have no items in your cart</i></p></td></tr>
              @else
              
              @foreach($content as $item)
                <tr>
                <td class="romove-item"><a href="{{ route('cart.remove',['id' => $item->id])}}" title="cancel" class="icon"><i class="fa fa-trash-o"></i></a></td>
                  <td class="cart-image">
                  <a class="entry-thumbnail" href="{{route('product.detail',['id'=>$item->attributes['slug']])}}"><img src="{{asset($item->attributes['image'])}}" alt=""></a>
                  </td>
                  <td class="cart-product-name-info">
                    <h4 class='cart-product-description'><a href="detail.html">{{$item->name}}</a></h4>
                    <div class="row">
                      <div class="col-sm-4">
                      @if($item->attributes['discount'])
                      <div class="rating rateit-small"><em style="color:green">Discount {{$item->attributes['discount']}}%</em></div>
                      @endif
                      </div>
                    </div><!-- /.row -->
                    <div class="cart-product-info">
                        {{-- <span class="product-color">COLOR:<span>Blue</span></span> --}}
                    </div>
                  </td>
                <td class="cart-product-name-info" style="width:auto">
                  <span class="cart-sub-total-price" style="font-weight:700px;font-size:16px"> ₦{{number_format($item->getPriceWithConditions(),2)}} </span>
                  
                </td>
                  <td class="cart-product-edit">
                      @if($item->attributes['discount'])
                        <span style="color:grey"><strike>₦{{$item->formated_price}}</strike></span>
                      @endif
                  </td>
                  <td class="cart-product-quantity">
                    <div class="quant-input">
                      <div class="arrows">
                      <div class="arrow plus gradient"><a href="{{ route('cart.incr',['id' => $item->id])}}" ><span class="ir"><i class="icon fa fa-sort-asc"></i></span></a></div>
                        <div class="arrow minus gradient"><a href="{{ route('cart.decr',['id' => $item->id])}}"><span class="ir"><i class="icon fa fa-sort-desc"></i></span></a></div>
                      </div>
                      <input type="text" value="{{$item->quantity}}">
                    </div>
                  </td>
                  <td class="cart-product-sub-total"><span class="cart-sub-total-price">₦{{number_format($item->getPriceSumWithConditions(),2)}}</span></td>
                </tr>
              @endforeach
              @endif
            </tbody><!-- /tbody -->
          </table><!-- /table -->
        </div>
      </div><!-- /.shopping-cart-table -->				
      <div class="col-md-4 col-sm-12 estimate-ship-tax">
      </div><!-- /.estimate-ship-tax -->
      
      <div class="col-md-4 col-sm-12 estimate-ship-tax">
        <table class="table">
          <thead>
          </thead>
        </table><!-- /table -->
      </div><!-- /.estimate-ship-tax -->
      
      <div class="col-md-4 col-sm-12 cart-shopping-total">
        <table class="table">
          <thead>
            <tr>
              <th>
              <div class="cart-sub-total" style="text-align:right;">VAT &nbsp;<span class="inner-left-md" style="margin-right:20px">7.2 %</span></div>
                <div class="cart-sub-total">Subtotal<span class="inner-left-md">₦{{number_format(Cart::getSubTotal(),2)}}</span></div>
                <div class="cart-grand-total">Grand Total<span class="inner-left-md">₦{{number_format(Cart::getTotal(),2)}}</span></div>
              </th>
            </tr>
          </thead><!-- /thead -->
          <tbody>
              <tr>
                <td>
                  <div class="cart-checkout-btn pull-right">
                    <a href="{{ route('checkout')}}" type="submit" class="btn btn-primary">PROCCED TO CHEKOUT</a>
                    {{-- <span class="">Checkout with multiples address!</span> --}}
                  </div>
                </td>
              </tr>
          </tbody><!-- /tbody -->
        </table><!-- /table -->
      </div><!-- /.cart-shopping-total -->			
    </div><!-- /.shopping-cart -->
  </div> <!-- /.row -->
</div>
</div>
@endsection

resources/views/shop/checkout.blade.php
@extends('shop.layout.main')

@section('content')
<div class="breadcrumb">
    <div class="container">
      <div class="breadcrumb-inner">
        <ul class="list-inline list-unstyled">
        <li><a href="{{ route('shop.home')}}">Home</a></li>
          <li class='active'>Checkout</li>
        </ul>
      </div><!-- /.breadcrumb-inner -->
    </div><!-- /.container -->
  </div>

  <div class="body-content outer-top-xs">
      <div class="container">
        <div class="row ">
          <div class="shopping-cart">
            <div class="shopping-cart-table ">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              {{-- <th class="cart-romove item">Remove</th> --}}
              <th class="cart-description item">Image</th>
              <th class="cart-product-name item">Name</th>
              <th class="cart-product-name item">Price</th>
              <th class="cart-edit item"></th>
              {{-- <th class="cart-qty item">Quantity</th> --}}
              <th class="cart-sub-total item">Subtotal</th>
            </tr>
          </thead><!-- /thead -->
          <tfoot>
            <tr>
              <td colspan="7">
                <div class="shopping-cart-btn">
                  <span class="">
                    <a href="{{ route('shop.home')}}" class="btn btn-upper btn-primary outer-left-xs">Continue Shopping</a>
                    {{-- <a href="#" class="btn btn-upper btn-primary pull-right outer-right-xs">Update shopping cart</a> --}}
                  </span>
                </div><!-- /.shopping-cart-btn -->
              </td>
            </tr>
          </tfoot>
          <tbody>
            @foreach(Cart::getContent() as $item)
              <tr>
              {{-- <td class="romove-item"><a href="{{ route('cart.remove',['id' => $item->id])}}" title="cancel" class="icon"><i class="fa fa-trash-o"></i></a></td> --}}
                <td class="cart-image">
                <a class="entry-thumbnail" href="{{route('product.detail',['id'=>$item->attributes['slug']])}}"><img src="{{asset($item->attributes['image'])}}" alt=""></a>
                </td>
                <td class="cart-product-name-info">
                  <h4 class='cart-product-description'><a href="{{route('product.detail',['id'=>$item->attributes['slug']])}}">{{$item->name}}</a></h4>
                  <div class="row">
                    <div class="col-sm-4">
                    @if($item->attributes['discount'])
                    <div class="rating rateit-small"><em style="color:green">Discount {{$item->attributes['discount']}}%</em></div>
                    @endif
                    </div>
                  </div><!-- /.row -->
                  <div class="cart-product-info">
                      {{-- <span class="product-color">COLOR:<span>Blue</span></span> --}}
                  </div>
                </td>
              <td class="cart-product-name-info" style="width:auto">
                <span class="cart-sub-total-price" style="font-weight:700px;font-size:16px"> ₦{{number_format($item->getPriceWithConditions())}} </span>
              </td>
                <td class="cart-product-edit">
                    @if($item->attributes['discount'])
                      <span style="color:grey"><strike>₦ {{number_format($item->price,2)}}</strike></span>
                    @endif
                </td>
                <td class="cart-product-sub-total"><span class="cart-sub-total-price">₦{{number_format($item->getPriceSumWithConditions(),2)}}</span></td>
              </tr>
            @endforeach
          </tbody><!-- /tbody -->
        </table><!-- /table -->
      </div>
    </div><!-- /.shopping-cart-table -->				
    <div class="col-md-4 col-sm-12 estimate-ship-tax">
    </div><!-- /.estimate-ship-tax -->
    
    <div class="col-md-4 col-sm-12 estimate-ship-tax">
      <table class="table">
        <thead>
        </thead>
      </table><!-- /table -->
    </div><!-- /.estimate-ship-tax -->
    
    <div class="col-md-4 col-sm-12 cart-shopping-total">
      <table class="table">
        <thead>
          <tr>
            <th>
              <div class="cart-sub-total" style="text-align:right;">VAT &nbsp;<span class="inner-left-md" style="margin-right:38px">7.2%</span></div>
              <div class="cart-sub-total">Subtotal<span class="inner-left-md">₦{{number_format(Cart::getSubTotal(),2)}}</span></div>
              <div class="cart-grand-total">Grand Total<span class="inner-left-md">₦{{number_format(Cart::getTotal(),2)}}</span></div>
            </th>
          </tr>
        </thead><!-- /thead -->
        <tbody>
            <tr>
              <td>
                  <div class="cart-checkout-btn pull-left">
                      <form method="POST" action="{{ route('pay') }}" accept-charset="UTF-8" class="form-horizontal" role="form">
                        @csrf
                          <div class="row" style="margin-bottom:40px;">
                              <input type="hidden" name="email" value="just@gmail.com"> {{-- required --}}
                              <input type="hidden" name="orderID" value="345">                       
                              <input type="hidden" name="amount" value="{{Cart::getTotal()*100}}"> {{-- required in kobo --}}
                              <input type="hidden" name="quantity" value="{{Cart::getTotalQuantity()}}">
                              <input type="hidden" name="metadata" value="{{ json_encode($array = ['id' => Auth::user()->id]) }}" >
                              <input type="hidden" name="reference" value="{{ Paystack::genTranxRef() }}"> {{-- required --}}
                              <input type="hidden" name="key" value="{{ config('paystack.secretKey') }}"> {{-- required --}}                  
                              <button class="btn btn-success" type="submit" value="Pay Now!"><i class="fa fa-plus-circle fa-lg"></i> Pay Now!</button>
                            </div>
                          </div>
                    </form>
                  </div>
                <div class="cart-checkout-btn pull-right" style="margin-left:10px">
                <a href="{{ route('cash.delivery') }}" class="btn btn-info"><i class="fa fa-plus-circle fa-lg"></i> Cash On Delivery</a>
                </div>
              </td>
            </tr>
        </tbody><!-- /tbody -->
      </table><!-- /table -->
    </div><!-- /.cart-shopping-total -->			
  </div><!-- /.shopping-cart -->
</div> <!-- /.row -->
</div>
</div>
@endsection